### ISSUE TITLE
yacman update

### ISSUE THREAD

**Issue by nsheff** [pepkit/divvy#56]
```
looper run bioinformatics_demo/pep_bio.yaml
Looper version: 1.3.1-dev
Command: run
/home/nsheff/.local/lib/python3.8/site-packages/yacman/yacman.py:365: UserWarning: The 'file_path' property is deprecated and will be removed in a future release. Use ComputingConfiguration.__internal.file_path instead.
  warn(
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 963, in main
    p = Project(cfg=args.config_file,
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 106, in __init__
    ComputingConfiguration(filepath=divcfg_path)
  File "/home/nsheff/.local/lib/python3.8/site-packages/divvy/compute.py", line 68, in __init__
    self.activate_package(DEFAULT_COMPUTE_RESOURCES_NAME)
  File "/home/nsheff/.local/lib/python3.8/site-packages/divvy/compute.py", line 165, in activate_package
    os.path.dirname(self.file_path),
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 22, in __getattribute__
    res = super(PathExAttMap, self).__getattribute__(item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/yacman/yacman.py", line 338, in file_path
    _warn_deprecated(obj=self)
  File "/home/nsheff/.local/lib/python3.8/site-packages/yacman/yacman.py", line 369, in _warn_deprecated
    raise UserWarning
UserWarning
```

But when I switch to `self.__internal.file_path`, I get this error:

```
looper run bioinformatics_demo/pep_bio.yaml
Looper version: 1.3.1-dev
Command: run
_ComputingConfiguration__internal
Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 36, in __getattr__
    v = super(PathExAttMap, self).__getattribute__(item)
AttributeError: 'ComputingConfiguration' object has no attribute '_ComputingConfiguration__internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: '_ComputingConfiguration__internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 39, in __getattr__
    return self.__getitem__(item, expand)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 56, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: '_ComputingConfiguration__internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 963, in main
    p = Project(cfg=args.config_file,
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 106, in __init__
    ComputingConfiguration(filepath=divcfg_path)
  File "/home/nsheff/.local/lib/python3.8/site-packages/divvy/compute.py", line 69, in __init__
    self.config_file = self.__internal.file_path
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 43, in __getattr__
    raise AttributeError(item)
AttributeError: _ComputingConfiguration__internal
```

**Comment by nsheff** [comment]
You can also get the error with something very simple:

```
In [5]: import divvy

In [6]: divvy.ComputingConfiguration({})
_ComputingConfiguration__internal
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py in __getattr__(self, item, default, expand)
     35         try:
---> 36             v = super(PathExAttMap, self).__getattribute__(item)
     37         except AttributeError:

AttributeError: 'ComputingConfiguration' object has no attribute '_ComputingConfiguration__internal'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/attmap/ordattmap.py in __getitem__(self, item)
     44         try:
---> 45             return super(OrdAttMap, self).__getitem__(item)
     46         except KeyError:

KeyError: '_ComputingConfiguration__internal'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py in __getattr__(self, item, default, expand)
     38             try:
---> 39                 return self.__getitem__(item, expand)
     40             except KeyError:

~/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py in __getitem__(self, item, expand, to_dict)
     55         """
---> 56         v = super(PathExAttMap, self).__getitem__(item)
     57         return _safely_expand(v, to_dict) if expand else v

~/.local/lib/python3.8/site-packages/attmap/ordattmap.py in __getitem__(self, item)
     46         except KeyError:
---> 47             return AttMap.__getitem__(self, item)
     48 

~/.local/lib/python3.8/site-packages/attmap/attmap.py in __getitem__(self, item)
     31     def __getitem__(self, item):
---> 32         return self.__dict__[item]
     33 

KeyError: '_ComputingConfiguration__internal'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-6-eddfdebc43a1> in <module>
----> 1 divvy.ComputingConfiguration({})

~/.local/lib/python3.8/site-packages/divvy/compute.py in __init__(self, entries, filepath)
     67         self.setdefault("adapters", None)
     68         self.activate_package(DEFAULT_COMPUTE_RESOURCES_NAME)
---> 69         self.config_file = self.__internal.file_path
     70 
     71     def write(self, filename=None):

~/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py in __getattr__(self, item, default, expand)
     41                 # Requested item is unknown, but request was made via
     42                 # __getitem__ syntax, not attribute-access syntax.
---> 43                 raise AttributeError(item)
     44         else:
     45             return _safely_expand(v) if expand else v

AttributeError: _ComputingConfiguration__internal
```

**Comment by nsheff** [comment]
This is actually a bug in yacman.

Basically, using `self.file_path` works, but gives a warning. Using `self.__internal.file_path` is broken. Using `self.__internal._file_path` is also broken.

**Comment by stolarczyk** [comment]
I'm using yacman 0.8.2-dev and this issue went away:

```python
In [4]: dcc.file_path
<ipython-input-4-2227b430a51e>:1: UserWarning: The 'file_path' property is deprecated and will be removed in a future release. Use ComputingConfiguration["__internal"][file_path] instead.
  dcc.file_path
Out[4]: '/Users/mstolarczyk/code/divcfg/uva_rivanna.yaml'

In [5]: dcc._file_path
<ipython-input-5-9b46e8738152>:1: UserWarning: The '_file_path' property is deprecated and will be removed in a future release. Use ComputingConfiguration["__internal"][_file_path] instead.
  dcc._file_path
Out[5]: '/Users/mstolarczyk/code/divcfg/uva_rivanna.yaml'

In [6]: dcc.__internal
Out[6]: 
AttMap
wait_time: 60
file_path: /Users/mstolarczyk/code/divcfg/uva_rivanna.yaml
ro: True
write_validate: True
schema:
  description: divvy configuration file schema
  version: 0.1
  required: 
   - compute_packages
  properties:
    compute_packages:
      type: object
      additionalProperties: False
      patternProperties:
        ^.*$:
          type: object
          additionalProperties: False
          patternProperties:
            ^.*$:
              type: string
    adapters:
      type: object
      additionalProperties: False
      patternProperties:
        ^.*$:
          type: string

In [7]: dcc.__internal.file_path
Out[7]: '/Users/mstolarczyk/code/divcfg/uva_rivanna.yaml'
```

maybe we should require yacman 0.8.2 for the upcoming release of divvy?

**Comment by stolarczyk** [comment]
there are no relevant changes to this issue on dev (0.8.2), so requiring 0.8.1 (released) will for just as fine.

**Comment by nsheff** [comment]
sounds fine with me
